CALL new_location('Northern Undead Asylum (tutorial)');
CALL new_location('Firelink Shrine');
CALL new_location('Undead Burg (upper)');
CALL new_location('Undead Burg (lower)');
CALL new_location('Undead Parish');
CALL new_location('Northern Undead Asylum (return)');
CALL new_location('Depths');
CALL new_location('Blighttown');
CALL new_location('The Great Hollow');
CALL new_location('Ash Lake');
CALL new_location('Quelaag''s Domain');
CALL new_location('Daughter of Chaos');
CALL new_location('Valley of Drakes');
CALL new_location('Sen''s Fortress (inside)');
CALL new_location('Sen''s Fortress (rooftops)');
CALL new_location('Anor Londo');
CALL new_location('Painted World of Ariamis');
CALL new_location('Darkmoon Tomb');
CALL new_location('Chamber of the Princess');
CALL new_location('Darkroot Garden');
CALL new_location('Darkroot Wood');
CALL new_location('Darkroot Basin');
CALL new_location('New Londo Ruins (upper)');
CALL new_location('New Londo Ruins (lower)');
CALL new_location('The Abyss');
CALL new_location('Demon Ruins (upper)');
CALL new_location('Demon Ruins (lower)');
CALL new_location('Demon Ruins (arena)');
CALL new_location('Lost Izalith');
CALL new_location('The Catacombs');
CALL new_location('Tomb of the Giants (total darkness)');
CALL new_location('Tomb of the Giants (skeleton pool)');
CALL new_location('Altar of the Gravelord');
CALL new_location('The Duke''s Archives');
CALL new_location('Archives Prison');
CALL new_location('Crystal Cave');
CALL new_location('Firelink Altar');
CALL new_location('Kiln of the First Flame');
