CALL new_npc('Anastacia of Astora', 'Firelink Shrine', p_firekeeper=>'1');
CALL new_npc('Kingseeker Frampt', 'Firelink Shrine');
CALL new_merchant('Undead Merchant (male)', 'Undead Burg (upper)');
CALL new_merchant('Undead Merchant (female)', 'Undead Burg (lower)');
CALL new_npc('Solaire of Astora', 'Undead Burg (upper)');
CALL new_merchant('Andre of Astora', 'Undead Parish', '1');
CALL new_npc('Knight Lautrec of Carim', 'Firelink Shrine');
CALL new_merchant('Oswald of Carim', 'Undead Parish');
CALL new_npc('Alvina of the Darkroot Wood', 'Darkroot Wood', p_covenant=>'1');
CALL new_merchant('Shiva of the East', 'Blighttown');
CALL new_merchant('Domhnall of Zena (Depths)', 'Depths');
CALL new_merchant('Domhnall of Zena (Firelink)', 'Firelink Shrine');
CALL new_npc('The Fair Lady', 'Daughter of Chaos', '1', '1');
CALL new_npc('Siegmeyer of Catarina', 'Firelink Shrine');
CALL new_merchant('Crestfallen Merchant', 'Sen''s Fortress (rooftops)');
CALL new_merchant('Ingward', 'New Londo Ruins (upper)');
CALL new_npc('Darkstalker Kaathe', 'The Abyss', p_covenant=>'1');
CALL new_npc('Darkmoon Knightess', 'Anor Londo', p_firekeeper=>'1');
CALL new_npc('Princess Gwynevere', 'Chamber of the Princess', p_covenant=>'1');
CALL new_npc('Dark Sun Gwyndolin (NPC)', 'Darkmoon Tomb', p_covenant=>'1');
CALL new_merchant('Giant Blacksmith', 'Anor Londo', '1');
CALL new_merchant('Blacksmith Vamos', 'The Catacombs', '1');
CALL new_merchant('Patches the Hyena', 'Firelink Shrine');
CALL new_merchant('Griggs of Vinheim', 'Firelink Shrine');
CALL new_merchant('Rickert of Vinheim', 'New Londo Ruins (upper)', '1');
CALL new_merchant('Big Hat Logan (Firelink)', 'Firelink Shrine');
CALL new_merchant('Big Hat Logan (Archives)', 'The Duke''s Archives');
CALL new_merchant('Dusk of Oolacile', 'Darkroot Basin');
CALL new_merchant('Laurentius of the Great Swamp', 'Firelink Shrine');
CALL new_merchant('Quelana of Izalith', 'Blighttown');
CALL new_merchant('Eingyi', 'Daughter of Chaos');
CALL new_merchant('Petrus of Thorolund', 'Firelink Shrine');
CALL new_merchant('Reah of Thorolund', 'Undead Parish');
CALL new_npc('Altar of Sunlight', 'Undead Burg (upper)', p_covenant=>'1');
CALL new_npc('Everlasting Dragon', 'Ash Lake', p_covenant=>'1');
CALL new_npc('Gravelord Nito (NPC)', 'Altar of the Gravelord', p_covenant=>'1');
