CALL new_transit('Northern Undead Asylum (tutorial)', 'Firelink Shrine', 'one-sided warp');
CALL new_transit('Firelink Shrine', 'Undead Burg (upper)', 'normal transit');
CALL new_transit('Firelink Shrine', 'New Londo Ruins (upper)', 'elevator');
CALL new_transit('Firelink Shrine', 'The Catacombs', 'normal transit');
CALL new_transit('Undead Burg (upper)', 'Undead Burg (lower)', 'locked door');
CALL new_transit('Undead Burg (upper)', 'Undead Parish', 'normal transit');
CALL new_transit('Undead Burg (upper)', 'Undead Parish', 'one-sided door');
CALL new_transit('Undead Parish', 'Firelink Shrine', 'locked elevator');
CALL new_transit('Firelink Shrine', 'Northern Undead Asylum (return)', 'warp');
CALL new_transit('Undead Parish', 'Sen''s Fortress (inside)', 'locked door');
CALL new_transit('Undead Parish', 'Darkroot Garden', 'normal transit');
CALL new_transit('Undead Burg (lower)', 'Firelink Shrine', 'one-sided door');
CALL new_transit('Undead Burg (lower)', 'Undead Burg (upper)', 'one-sided door');
CALL new_transit('Undead Burg (lower)', 'Depths', 'boss fight');
CALL new_transit('Depths', 'Blighttown', 'boss fight');
CALL new_transit('Blighttown', 'The Great Hollow', 'illusion wall');
CALL new_transit('The Great Hollow', 'Ash Lake', 'normal transit');
CALL new_transit('Blighttown', 'Quelaag''s Domain', 'boss fight');
CALL new_transit('Quelaag''s Domain', 'Daughter of Chaos', 'illusion wall');
CALL new_transit('Quelaag''s Domain', 'Demon Ruins (upper)', 'normal transit');
CALL new_transit('Blighttown', 'Valley of Drakes', 'normal transit');
CALL new_transit('Valley of Drakes', 'New Londo Ruins (upper)', 'locked door');
CALL new_transit('Sen''s Fortress (inside)', 'Sen''s Fortress (rooftops)', 'normal transit');
CALL new_transit('Sen''s Fortress (rooftops)', 'Sen''s Fortress (inside)', 'locked elevator');
CALL new_transit('Sen''s Fortress (rooftops)', 'Anor Londo', 'warp');
CALL new_transit('Anor Londo', 'The Duke''s Archives', 'golden fog');
CALL new_transit('Anor Londo', 'Anor Londo', 'one-sided door');
CALL new_transit('Anor Londo', 'Anor Londo', 'one-sided door');
CALL new_transit('Anor Londo', 'Anor Londo', 'one-sided door');
CALL new_transit('Anor Londo', 'Anor Londo', 'one-sided door');
CALL new_transit('Anor Londo', 'Anor Londo', 'illusion wall');
CALL new_transit('Anor Londo', 'Chamber of the Princess', 'boss fight');
CALL new_transit('Anor Londo', 'Painted World of Ariamis', 'one-sided warp');
CALL new_transit('Painted World of Ariamis', 'Anor Londo', 'one-sided warp');
CALL new_transit('Anor Londo', 'Darkmoon Tomb', 'locked elevator');
CALL new_transit('Darkroot Garden', 'Darkroot Wood', 'locked door');
CALL new_transit('Darkroot Garden', 'Darkroot Basin', 'normal transit');
CALL new_transit('Darkroot Basin', 'Valley of Drakes', 'locked elevator');
CALL new_transit('Darkroot Basin', 'Undead Burg (upper)', 'locked door');
CALL new_transit('Darkroot Basin', 'Darkroot Wood', 'normal transit');
CALL new_transit('New Londo Ruins (upper)', 'New Londo Ruins (lower)', 'locked door');
CALL new_transit('New Londo Ruins (lower)', 'Valley of Drakes', 'one-sided door');
CALL new_transit('New Londo Ruins (lower)', 'The Abyss', 'normal transit');
CALL new_transit('Firelink Shrine', 'Firelink Altar', 'warp');
CALL new_transit('The Abyss', 'Firelink Altar', 'warp');
CALL new_transit('Demon Ruins (upper)', 'Demon Ruins (lower)', 'boss fight');
CALL new_transit('Demon Ruins (lower)', 'Demon Ruins (arena)', 'golden fog');
CALL new_transit('Demon Ruins (arena)', 'Quelaag''s Domain', 'locked elevator');
CALL new_transit('Demon Ruins (arena)', 'Lost Izalith', 'boss fight');
CALL new_transit('Lost Izalith', 'Demon Ruins (arena)', 'one-sided door');
CALL new_transit('The Catacombs', 'Altar of the Gravelord', 'warp');
CALL new_transit('The Catacombs', 'Tomb of the Giants (total darkness)', 'boss fight');
CALL new_transit('The Catacombs', 'Tomb of the Giants (total darkness)', 'one-sided warp');
CALL new_transit('Tomb of the Giants (total darkness)', 'The Catacombs', 'normal transit');
CALL new_transit('Tomb of the Giants (total darkness)', 'Tomb of the Giants (skeleton pool)', 'golden fog');
CALL new_transit('The Duke''s Archives', 'The Duke''s Archives', 'elevator');
CALL new_transit('The Duke''s Archives', 'Archives Prison', 'one-sided warp');
CALL new_transit('Archives Prison', 'The Duke''s Archives', 'locked door');
CALL new_transit('The Duke''s Archives', 'Crystal Cave', 'locked door');
CALL new_transit('Firelink Altar', 'Kiln of the First Flame', 'locked door');
