/* p_name, p_mag_dmg, p_fir_dmg, p_lig_dmg, p_holy_dmg, p_unholy_dmg */

CALL update_enemy_dmg('Hollow', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Undead Soldier', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Armored Hollow', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Small Rat', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Skeleton', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Giant Skeleton', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Black Knight', p_unholy_dmg=>'weak to');
CALL update_enemy_dmg('Hellkite Wyvern', p_fir_dmg=>'resistant', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Balder Knight (Sword)', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Balder Knight (Rapier)', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Fang Boar', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Channeler', 'resistant');
CALL update_enemy_dmg('Titanite Demon', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Large Rat', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Giant Rat', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Butcher', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Slime', 'resistant', 'weak to', 'resistant');
CALL update_enemy_dmg('Flaming Attack Dog', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Cragspider', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Mushroom Parent', 'weak to', 'weak to', 'resistant');
CALL update_enemy_dmg('Mushroom Child', 'weak to', 'weak to', 'resistant');
CALL update_enemy_dmg('Man-Eater Shell', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Egg Carrier', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Vile Maggot', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Blue Drake', p_fir_dmg=>'weak to', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Undead Dragon', p_fir_dmg=>'weak to', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Serpent Soldier', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Serpent Mage', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Balder Knight (Crossbow)', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Sentinel', p_unholy_dmg=>'weak to');
CALL update_enemy_dmg('Anor Londo Gargoyle', p_fir_dmg=>'weak to', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Batwing Demon', p_fir_dmg=>'weak to', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Silver Knight', p_unholy_dmg=>'weak to');
CALL update_enemy_dmg('Royal Sentinel', p_unholy_dmg=>'weak to');
CALL update_enemy_dmg('Engorged Hollow', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Harpy', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Snow Rat', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Phalanx', 'resistant', 'weak to');
CALL update_enemy_dmg('Skeleton Wheel', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Ent', p_fir_dmg=>'weak to');
CALL update_enemy_dmg('Giant Stone Knight', p_fir_dmg=>'weak to', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Giant Cat', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Crystal Golem', 'resistant');
CALL update_enemy_dmg('Golden Crystal Golem', 'resistant');
CALL update_enemy_dmg('Ghost', p_lig_dmg=>'resistant');
CALL update_enemy_dmg('Darkwraith', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Mass of Souls', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Burrowing Rockworm', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Demonic Statue', 'weak to', 'resistant', 'resistant');
CALL update_enemy_dmg('Chaos Bug', 'weak to', 'resistant');
CALL update_enemy_dmg('Bounding Demon of Izalith', p_fir_dmg=>'resistant', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Chaos Eater', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Lost Izalith Pyromancer', p_fir_dmg=>'resistant');
CALL update_enemy_dmg('Skeleton Archer', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Giant Skeleton Archer', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Skeleton Beast', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Bone Tower', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Skeleton Baby', p_holy_dmg=>'weak to');
CALL update_enemy_dmg('Undead Crystal Soldier', p_mag_dmg=>'resistant', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Pisaca', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
CALL update_enemy_dmg('Minor Moonlight Butterfly', p_fir_dmg=>'weak to', p_lig_dmg=>'weak to');
