CALL new_item ('Humanity');
CALL new_item ('Twin Humanities');
CALL new_item ('Fire Keeper Soul');
CALL new_item ('Divine Blessing');
CALL new_item ('Repair Powder');
CALL new_item ('Transient Curse');
CALL new_item ('Homeward Bone');
CALL new_item ('Green Blossom');
CALL new_item ('Bloodred Moss Clump');
CALL new_item ('Purple Moss Clump');
CALL new_item ('Blooming Purple Moss Clump');
CALL new_item ('Purging Stone');
CALL new_item ('Charcoal Pine Resin');
CALL new_item ('Rotten Pine Resin');
CALL new_item ('Gold Pine Resin');
CALL new_item ('Egg Vermifuge');
CALL new_item ('Eye of Death');
CALL new_item ('Sunlight Medal');
CALL new_item ('Souvenir of Reprisal');
CALL new_item ('Firebomb');
CALL new_item ('Black Firebomb');
CALL new_item ('Dung Pie');
CALL new_item ('Alluring Skull');
CALL new_item ('Copper Coin');
CALL new_item ('Silver Coin');
CALL new_item ('Gold Coin');
