/* name, type, slots, uses, effect_type, effect_subtype, p_int_req, p_fth_req */

CALL new_spell('Soul Arrow', 'sorcery', 1, 30, 'ranged attack', p_int_req=>10);
CALL new_spell('Great Soul Arrow', 'sorcery', 1, 20, 'ranged attack', p_int_req=>14);
CALL new_spell('Heavy Soul Arrow', 'sorcery', 1, 12, 'ranged attack', p_int_req=>12);
CALL new_spell('Great Heavy Soul Arrow', 'sorcery', 1, 8, 'ranged attack', p_int_req=>16);
CALL new_spell('Homing Soulmass', 'sorcery', 1, 10, 'ranged attack', p_int_req=>18);
CALL new_spell('Homing Crystal Soulmass', 'sorcery', 1, 10, 'ranged attack', p_int_req=>24);
CALL new_spell('Soul Spear', 'sorcery', 1, 4, 'ranged attack', p_int_req=>36);
CALL new_spell('Crystal Soul Spear', 'sorcery', 1, 4, 'ranged attack', p_int_req=>44);
CALL new_spell('White Dragon Breath', 'sorcery', 1, 20, 'ranged attack', p_int_req=>50);
CALL new_spell('Magic Weapon', 'sorcery', 1, 5, 'weapon buff', p_int_req=>10);
CALL new_spell('Great Magic Weapon', 'sorcery', 1, 3, 'weapon buff', p_int_req=>15);
CALL new_spell('Crystal Magic Weapon', 'sorcery', 1, 3, 'weapon buff', p_int_req=>25);
CALL new_spell('Magic Shield', 'sorcery', 1, 5, 'support', 'defense buff', p_int_req=>10);
CALL new_spell('Strong Magic Shield', 'sorcery', 1, 3, 'support', 'defense buff', p_int_req=>15);
CALL new_spell('Aural Decoy', 'sorcery', 1, 20, 'support', p_int_req=>10);
CALL new_spell('Hush', 'sorcery', 1, 6, 'buff', p_int_req=>15);
CALL new_spell('Fall Control', 'sorcery', 1, 10, 'buff', p_int_req=>15);
CALL new_spell('Hidden Weapon', 'sorcery', 1, 3, 'support', 'weapon buff', p_int_req=>14);
CALL new_spell('Hidden Body', 'sorcery', 1, 3, 'buff', p_int_req=>14);
CALL new_spell('Repair', 'sorcery', 1, 1, 'support', p_int_req=>14);
CALL new_spell('Cast Light', 'sorcery', 1, 3, 'buff', p_int_req=>14);
CALL new_spell('Chameleon', 'sorcery', 1, 11, 'buff', p_int_req=>14);
CALL new_spell('Remedy', 'sorcery', 1, 4, 'support', p_int_req=>16);
CALL new_spell('Resist Curse', 'sorcery', 1, 4, 'support', p_int_req=>16);

CALL new_spell('Fireball', 'pyromancy', 1, 8, 'short range attack', 'small AoE');
CALL new_spell('Fire Orb', 'pyromancy', 1, 6, 'short range attack', 'small AoE');
CALL new_spell('Great Fireball', 'pyromancy', 1, 4, 'short range attack', 'AoE');
CALL new_spell('Great Chaos Fireball', 'pyromancy', 2, 4, 'short range attack', 'AoE');
CALL new_spell('Firestorm', 'pyromancy', 1, 20, 'AoE attack');
CALL new_spell('Fire Tempest', 'pyromancy', 1, 20, 'AoE attack');
CALL new_spell('Chaos Storm', 'pyromancy', 2, 20, 'AoE attack');
CALL new_spell('Combustion', 'pyromancy', 1, 16, 'melee range attack');
CALL new_spell('Great Combustion', 'pyromancy', 1, 8, 'melee range attack');
CALL new_spell('Fire Surge', 'pyromancy', 1, 80, 'melee range attack');
CALL new_spell('Fire Whip', 'pyromancy', 1, 80, 'melee range attack');
CALL new_spell('Chaos Fire Whip', 'pyromancy', 2, 80, 'melee range attack');
CALL new_spell('Poison Mist', 'pyromancy', 1, 3, 'AoE debuff');
CALL new_spell('Toxic Mist', 'pyromancy', 1, 1, 'AoE debuff');
CALL new_spell('Acid Surge', 'pyromancy', 1, 2, 'AoE debuff');
CALL new_spell('Flash Sweat', 'pyromancy', 1, 3, 'buff');
CALL new_spell('Iron Flesh', 'pyromancy', 1, 3, 'buff');
CALL new_spell('Power Within', 'pyromancy', 1, 1, 'buff');
CALL new_spell('Undead Rapport', 'pyromancy', 1, 7, 'buff');

CALL new_spell('Heal', 'miracle', 1, 5, 'heal', p_fth_req=>12);
CALL new_spell('Great Heal Excerpt', 'miracle', 1, 1, 'heal', p_fth_req=>14);
CALL new_spell('Great Heal', 'miracle', 1, 3, 'heal', p_fth_req=>24);
CALL new_spell('Soothing Sunlight', 'miracle', 2, 3, 'heal', 'AoE', p_fth_req=>48);
CALL new_spell('Replenishment', 'miracle', 1, 2, 'healing buff', p_fth_req=>16);
CALL new_spell('Bountiful Sunlight', 'miracle', 2, 2, 'healing buff', 'AoE', p_fth_req=>36);
CALL new_spell('Force', 'miracle', 1, 21, 'AoE attack', p_fth_req=>12);
CALL new_spell('Wrath of the Gods', 'miracle', 1, 3, 'AoE attack', p_fth_req=>28);
CALL new_spell('Emit Force', 'miracle', 1, 6, 'short range attack', 'AoE', p_fth_req=>18);
CALL new_spell('Magic Barrier', 'miracle', 1, 4, 'support', 'defense buff', p_fth_req=>14);
CALL new_spell('Great Magic Barrier', 'miracle', 1, 2, 'support', 'defense buff', p_fth_req=>24);
CALL new_spell('Homeward', 'miracle', 1, 1, 'support', p_fth_req=>18);
CALL new_spell('Seek Guidance', 'miracle', 1, 5, 'support', p_fth_req=>12);
CALL new_spell('Karmic Justice', 'miracle', 1, 4, 'buff', p_fth_req=>20);
CALL new_spell('Vow of Silence', 'miracle', 2, 2, 'AoE debuff', p_fth_req=>30);
CALL new_spell('Tranquil Walk of Peace', 'miracle', 1, 5, 'AoE debuff', p_fth_req=>18);
CALL new_spell('Lightning Spear (miracle)', 'miracle', 1, 10, 'ranged attack', p_fth_req=>20);
CALL new_spell('Great Lightning Spear', 'miracle', 1, 10, 'ranged attack', p_fth_req=>30);
CALL new_spell('Sunlight Spear', 'miracle', 2, 5, 'ranged attack', p_fth_req=>50);
CALL new_spell('Sunlight Blade', 'miracle', 1, 1, 'weapon buff', p_fth_req=>30);
CALL new_spell('Darkmoon Blade', 'miracle', 1, 1, 'weapon buff', p_fth_req=>30);
CALL new_spell('Gravelord Sword Dance', 'miracle', 1, 40, 'AoE attack');
CALL new_spell('Gravelord Greatsword Dance', 'miracle', 1, 40, 'AoE attack');
